### ISSUE TITLE
Failed when using the linestyle attribute

### ISSUE THREAD

**Issue by MarviCode** [mrkn/matplotlib.rb#17]
There is a bug when using the linestyle attribute in plot

```
require 'matplotlib/pyplot'

plt=Matplotlib::Pyplot

x1,y1,x2,y2 = 1,1,5,5


plt.xlim(0,10)
plt.ylim(0,10)
plt.plot([x1,x2],[y1,y2],linestyle='dashed')
plt.show

```

Without the linestyle attribute, it works fine while entering linestyle results in the following error:

```
.rvm/gems/ruby-3.1.1/gems/pycall-1.4.1/lib/pycall/pyobject_wrapper.rb:43:in `plot': <class 'ValueError'>: Unrecognized character a in format string (PyCall::PyError)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/pyplot.py", line 2761, in plot
    return gca().plot(
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/axes/_axes.py", line 1647, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/axes/_base.py", line 216, in __call__
    yield from self._plot_args(this, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/axes/_base.py", line 312, in _plot_args
    linestyle, marker, color = _process_plot_format(tup[-1])
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/axes/_base.py", line 104, in _process_plot_format
    raise ValueError(
	from /home/marvi/.rvm/gems/ruby-3.1.1/gems/pycall-1.4.1/lib/pycall/pyobject_wrapper.rb:43:in `method_missing'
	from matplt-ruby.rb:10:in `<main>'

```

**Comment by mrkn** [comment]
@MarviCode Use the correct keyword argument syntax.

```ruby
plt.plot([x1,x2],[y1,y2],linestyle: 'dashed')
```

**Comment by MarviCode** [comment]
Thank you very much
