### ISSUE TITLE
require failing after installing gem

### ISSUE THREAD

**Issue by mhuggins** [mrkn/matplotlib.rb#3]
Hi there.  I just tried to use this gem for the first time, but it does not seem to be working.

> ➜ gem install --pre matplotlib
> Fetching: pycall-0.1.0.alpha.20170502.gem (100%)
> Successfully installed pycall-0.1.0.alpha.20170502
> Fetching: matplotlib-0.1.0.alpha.20170426.gem (100%)
> Successfully installed matplotlib-0.1.0.alpha.20170426
> Parsing documentation for pycall-0.1.0.alpha.20170502
> Installing ri documentation for pycall-0.1.0.alpha.20170502
> Parsing documentation for matplotlib-0.1.0.alpha.20170426
> Installing ri documentation for matplotlib-0.1.0.alpha.20170426
> Done installing documentation for pycall, matplotlib after 0 seconds
> 2 gems installed
> 
> ➜ irb
> 2.3.2 :001 > require 'matplotlib/pyplot'
> LoadError: cannot load such file -- matplotlib/pyplot
> 2.3.2 :001 > require 'matplotlib'
> LoadError: cannot load such file -- matplotlib

**Comment by mrkn** [comment]
Show me the contents of `$LOAD_PATH`.

**Comment by cdcooksey** [comment]
Bump.  

```bash
$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
```

```ruby
$ cat Gemfile
source 'https://rubygems.org' do
  gem 'matplotlib'
end
```

```ruby
$ irb
irb(main):001:0> require 'matplotlib/pyplot'
PyCall::PyError: <type 'exceptions.ImportError'>: No module named matplotlib
	from /Users/charliecooksey/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pycall-1.0.3/lib/pycall.rb:52:in `import_module'
	from /Users/charliecooksey/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pycall-1.0.3/lib/pycall.rb:52:in `import_module'
	from /Users/charliecooksey/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/matplotlib-1.0.0/lib/matplotlib.rb:4:in `<top (required)>'
	from /Users/charliecooksey/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/charliecooksey/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/charliecooksey/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/matplotlib-1.0.0/lib/matplotlib/pyplot.rb:1:in `<top (required)>'
	from /Users/charliecooksey/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /Users/charliecooksey/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /Users/charliecooksey/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from (irb):1
	from /Users/charliecooksey/.rbenv/versions/2.2.3/bin/irb:11:in `<main>'
```


`$LOAD_PATH:`

```ruby
irb(main):002:0> $LOAD_PATH
=> ["/usr/local/Cellar/rbenv/1.1.0/rbenv.d/exec/gem-rehash", "/Users/charliecooksey/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-14/2.2.0-static/pycall-1.0.3", "/Users/charliecooksey/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/pycall-1.0.3/lib", "/Users/charliecooksey/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/matplotlib-1.0.0/lib", "/Users/charliecooksey/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0", "/Users/charliecooksey/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/x86_64-darwin14", "/Users/charliecooksey/.rbenv/versions/2.2.3/lib/ruby/site_ruby", "/Users/charliecooksey/.rbenv/versions/2.2.3/lib/ruby/vendor_ruby/2.2.0", "/Users/charliecooksey/.rbenv/versions/2.2.3/lib/ruby/vendor_ruby/2.2.0/x86_64-darwin14", "/Users/charliecooksey/.rbenv/versions/2.2.3/lib/ruby/vendor_ruby", "/Users/charliecooksey/.rbenv/versions/2.2.3/lib/ruby/2.2.0", "/Users/charliecooksey/.rbenv/versions/2.2.3/lib/ruby/2.2.0/x86_64-darwin14"]
```

**Comment by mrkn** [comment]
@cdcooksey You have to install matplotlib in Python side before you use it from Ruby.

**Comment by cdcooksey** [comment]
@mrkn Ah! 😆 That makes sense.  Thanks!

**Comment by mrkn** [comment]
@mhuggins I closed this issue. Please open the new issue if you still have problems.

**Comment by pmontrasio** [comment]
This should be into the install section of the README.

```
pip install matplotlib
```
