### ISSUE TITLE
IRuby NoMethodError instead of error message

### ISSUE THREAD

**Issue by dhnam** [mrkn/matplotlib.rb#9]
I'm using this in IRuby running on google colaboratory.

When I interrupt running program, it gave me
```
NoMethodError: undefined method `error_message' for #<IRuby::Kernel:0x00005590dda4c1a8>
```
instead of `KeyboardInturrupted`.

Here is detailed error message:
```
/var/lib/gems/2.5.0/gems/matplotlib-1.0.0/lib/matplotlib/iruby.rb:64:in `rescue in execute_request'
/var/lib/gems/2.5.0/gems/matplotlib-1.0.0/lib/matplotlib/iruby.rb:59:in `execute_request'
/var/lib/gems/2.5.0/gems/iruby-0.3/lib/iruby/kernel.rb:50:in `dispatch'
/var/lib/gems/2.5.0/gems/iruby-0.3/lib/iruby/kernel.rb:39:in `run'
/var/lib/gems/2.5.0/gems/iruby-0.3/lib/iruby/command.rb:110:in `run_kernel'
/var/lib/gems/2.5.0/gems/iruby-0.3/lib/iruby/command.rb:40:in `run'
/var/lib/gems/2.5.0/gems/iruby-0.3/bin/iruby:5:in `<top (required)>'
/usr/local/bin/iruby:23:in `load'
/usr/local/bin/iruby:23:in `<main>'
```

**Comment by dhnam** [comment]
...And it does not halts, so every time I want to interrupt running program, I have to restart runtime.
